version: "2"

services:
  wordpress_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: azerty
      MYSQL_USER: jojo
      MYSQL_PASSWORD: azerty
  wordpress:
    image: wordpress
    links:
      - wordpress_db:mysql
    ports:
      - 8080:80
    restart: always
